name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: |
          dotnet test tests/RankLib.Tests --no-build --verbosity normal
          dotnet test tests/RankLib.Cli.Tests --no-build --verbosity normal

  publish-docs:
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Publish documentation
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install docfx
        run: dotnet tool update -g docfx
      - name: Run docfx
        run: docfx docs/Docs/docfx.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload site only
          path: './docs/Docs/_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1    